baseURL = 'https://jasinski.us/'
languageCode = 'en-us'
title = 'Slawomir Jasinski landing page'
theme = "anatole"

[taxonomies]
category = "categories"
tag = "tags"

[params]
title = "Blog Architekta"
author = "Slawomir Jasinski"
copyright = "2011-2024"
description = "Forward-thinking Solutions Architect excels in cloud migration, optimizing infrastructure for peak performance and security, deploying tailored solutions."
mainSections = ["post"]
enableMediumZoom = true
assetDir = "assets"
contentratio = 0.7
profilePicture = "images/DSF1609.jpg"
customCss = ["css/custom.css"]
reversepagetitle = true
gtagId = "G-S3DZNELTH9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[permalinks]
#categories = "/category/:slug/"

[[Languages.en.menu.main]]
url = "/posts/"
identifier = "Blog"
name   = "Blog"
weight = 10

[[Languages.en.menu.main]]
url = "/categories/arduino/"
identifier = "arduino"
name   = "Arduino"
weight = 25

[[Languages.en.menu.main]]
url = "/categories/work/"
identifier = "work"
name   = "Work"
weight = 30

[[Languages.pl.menu.main]]
url = "/pl/categories/blog/"
identifier = "blog"
name   = "Blog"
weight = 25

[[Languages.pl.menu.main]]
url = "/pl/categories/praca/"
identifier = "praca"
name   = "Praca"
weight = 30

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/slawomirjasinski"

[[params.socialIcons]]
icon = "fab fa-github"
tutle = "GitHub"
url = "https://github.com/slav123"

[[params.socialIcons]]
icon = "fab fa-stack-overflow"
title = "Stack Overflow"
url = "https://stackoverflow.com/users/432573/"

[[params.socialIcons]]
icon = "fab fa-twitter"
tutle = "Twitter"
url = "https://twitter.com/slavomirj"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/slavomirj/"

[[params.socialIcons]]
icon = "fas fa-business-time"
title = "business"
url = "https://www.yakconsulting.com"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:slav123@gmail.com"

[Languages]
[Languages.en]
title = "Slawomir Slav Jasinski"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[Languages.pl]
title = "Sławomir Jasiński"
description = "Ekspert w migracji do chmury, optymalizuje infrastrukturę dla wydajności i bezpieczeństwa. Specjalizuje się w innowacyjnych rozwiązaniach i procesach."
weight = 2
LanguageName = "PL"
contentDir = "content/polski"

ignoreLogs = ['err-youtube-remote', 'warning-goldmark-raw-html']